"""
DNS 切换器
"""
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path


@dataclass
class DNSServer:
    name: str
    ip: str

PRESET_DNS = {
    "阿里": [DNSServer("阿里 Primary", "223.5.5.5"), DNSServer("阿里 Secondary", "223.6.6.6")],
    "114": [DNSServer("114 Primary", "114.114.114.114"), DNSServer("114 Secondary", "114.114.115.115")],
    "Google": [DNSServer("Google Primary", "8.8.8.8"), DNSServer("Google Secondary", "8.8.4.4")],
    "Cloudflare": [DNSServer("Cloudflare Primary", "1.1.1.1"), DNSServer("Cloudflare Secondary", "1.0.0.1")],
}

class DNSSwitcher:
    @staticmethod
    def get_current() -> list[str]:
        """获取当前DNS服务器"""
        if sys.platform == "linux":
            try:
                content = Path("/etc/resolv.conf").read_text()
                return [line.split()[1] for line in content.splitlines() if line.startswith("nameserver")]
            except (OSError, IndexError):
                return []
        elif sys.platform == "win32":
            result = subprocess.run(["netsh", "interface", "ip", "show", "dns"], capture_output=True, text=True)
            lines = []
            for line in result.stdout.splitlines():
                if "DNS" in line and "addresses" in line.lower():
                    parts = line.split()
                    for p in parts:
                        if p.replace(".", "").isdigit() and len(p.split(".")) == 4:
                            lines.append(p)
            return lines
        return []

    @staticmethod
    def set_dns(servers: list[str], interface: str = "") -> bool:
        """设置DNS"""
        if sys.platform == "linux":
            try:
                lines = []
                for s in servers:
                    lines.append(f"nameserver {s}")
                Path("/etc/resolv.conf").write_text("\n".join(lines) + "\n")
                return True
            except PermissionError:
                return False
        elif sys.platform == "win32":
            if not interface:
                interface = "Wi-Fi"
            for i, s in enumerate(servers):
                cmd = ["netsh", "interface", "ip", "set", "dns", interface, "static", s]
                if i > 0:
                    cmd = ["netsh", "interface", "ip", "add", "dns", interface, s, f"index={i+1}"]
                subprocess.run(cmd, capture_output=True)
            return True
        return False

    @staticmethod
    def reset_dns(interface: str = "") -> bool:
        """恢复DHCP DNS"""
        if sys.platform == "linux":
            try:
                Path("/etc/resolv.conf").write_text("# Generated by NetworkManager\n")
                return True
            except PermissionError:
                return False
        elif sys.platform == "win32":
            iface = interface or "Wi-Fi"
            subprocess.run(["netsh", "interface", "ip", "set", "dns", iface, "dhcp"], capture_output=True)
            return True
        return False
